### PR TITLE
Touch support

### LINKED ISSUE #80: Touch support: Everything that uses releases doesn't work
Like dragging a card into something and turning a card. Sometimes it does work but usually not.

* [x] Click events
* [x] Drag events

### PR DESCRIPTION
**Pull request by raatmarien**
Fixes #80

### CODE REVIEW

**Comment by jchmrt** [comment]
Turning a card around is still not working on my phone (Firefox Android) :(

Anything we can do to debug that?

**Comment by raatmarien** [comment]
Hmm, I should've tested Firefox... I guess the MouseEvent is structured slightly different or something. I'll look into it tonight

The dragging does work? Dragging into a hand or deck?

**Comment by raatmarien** [comment]
Seems to work on desktop Firefox with touch events and on Chrome Android, but not on Firefox Android. It is hard to debug why without a console...

**Comment by jchmrt** [comment]
Maybe you could use something [like this](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging) to debug it on android?

**Comment by raatmarien** [comment]
I've managed to reproduce the bug on firefox Linux. The problem is indeed that Firefox handles this slightly differently. I've switched to a better approach of calling preventDefault on the touch events. As explained here https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent. However, although this does work on Chrome, it doesn't seem to work on Firefox. If you have time to look into it, that would be great. Maybe I'll try again tomorrow.

**Comment by raatmarien** [comment]
Fixed now on (hopefully) all browsers. Instead of trying to correct the stupid (:p) behavior of browsers, we just depend on it now. Better to go with the stupidities of the web I think

**Pull request merged**
