### PR TITLE
New frontpage

### PR DESCRIPTION
**Pull request by jchmrt**
Although it is not perfect, I think this front page is a good start for a styled front page, it has:

- Clear calls to action, with NEW ROOM being the biggest
- Bright colors to indicate that this is a website for fun
- The name of the site and a small tagline
- Details of the project at the bottom

Mostly what I don't like about this page is the logo, which is not very clear or distinctive. So a next step would be making a nice clear logo.

image

### CODE REVIEW

**Comment by flori9** [comment]
Looks great!
I do agree the logo could be improved, although I have no better idea right now.
Also, I don't have the Anton font; it would be good to have a fallback font (right now, it's falling back to Times New Roman...). Note that most fonts are wider, which makes ABCDE overflow which doesn't look great. On my computer, it looks like this right now:
image

**Comment by jchmrt** [comment]
Oh wait you are right, I forgot to actually do the webfonts. I had added it to my TODOs, but I forgot!

**Comment by jchmrt** [comment]
Good that you mention it, I will look into it!

**Comment by jchmrt** [comment]
I think I have correctly fixed it, but it is hard for me to test since I already have the fonts on my system. @flori9 could you check whether the fonts are now correctly displayed on your system?

**Comment by raatmarien** [comment]
Works now :+1:

**Comment by jchmrt** [comment]
Now updated with the new front-page in red and a new logo and favicon.

### Frontpage
image

### Favicon
logo-2-favicon

**Comment by jchmrt** [comment]
I think it's ready to merge, how about you? @flori9 @raatmarien

**Comment by raatmarien** [comment]
I think it is great and ready as well

**Pull request merged**
