### PR TITLE
Deal cards feature

### LINKED ISSUE #122: Deal feature: Automatically deal out a certain amount of cards to each player
Probably as an option in the extra options of the decks.

### LINKED ISSUE #132: Cards from hand not recalled on Recall or removed when deck is removed
Because the State only looks on the table

### PR DESCRIPTION
**Pull request by raatmarien**
Fixes #122 

I'm not totally happy with how hidden the feature is in the ui, but we have a seperate issue for that: #127 

Also fixes #132

### CODE REVIEW

**Comment by raatmarien** [comment]
Also fixes #132

**Comment by flori9** [comment]
Nice feature, looks good overall! Some minor things that would be good to fix:

- If you change any setting in the window (e.g. cards per player) and press deal, the settings are reset in the animation where the window fades away. This makes a look like your settings were ignored, even though they actually weren't. Maybe the state should only be reset when the window is shown and not when it's hidden?
- If there are less than 7*|players| cards left in the deck, the default number of cards dealed should be lower.
- If there are very few cards left in the deck (e.g. just one with two players), the Cards per player box starts giving fractional values if you click the arrows. Dealing half a card per player isn't possible and I think it would be better not to show values like that.

**Comment by raatmarien** [comment]
Good ideas, fixed them all :). How about now?

**Comment by raatmarien** [comment]
Oh yeah, nice

**Pull request merged**
